name: Build, Test, and Deploy Server

on:
  push:
    branches:
      - '**'  # Run on any branch for testing
    paths:
      - 'Server/**'
      - '.github/workflows/deploy.yml'
  pull_request:
    branches:
      - '**'  # Run on PRs to any branch
    paths:
      - 'Server/**'

jobs:
  deploy:
    name: Build, Test, and Deploy Python Server
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./Server
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: 'Server/requirements*.txt'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt
      
      - name: Run tests
        run: |
          echo "Running tests with coverage..."
          pytest -v --cov --cov-report=term-missing --cov-report=xml
      
      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        if: always()
        with:
          files: ./Server/coverage.xml
          flags: server
          name: server-coverage
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
      - name: Setup Terraform
        if: github.event_name == 'push'  # Only setup Terraform for deployments
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.0"  # Specify a stable version
      
      - name: Deploy to AWS
        if: github.event_name == 'push'  # Deploy on any push for testing
        run: |
          chmod +x deploy.sh
          ./deploy.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
